# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jml/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jml/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-pretarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jml/Documents/Max\ 8/Packages/max-sdk/source/misc/morphograph/CMakeLists.txt))

/Users/jml/Documents/Max\ 8/Packages/max-sdk/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/jml/Documents/Max\ 8/Packages/max-sdk -B/Users/jml/Documents/Max\ 8/Packages/max-sdk/build
